import type { NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";
import Form from "../components/Form";
import { IpInfoState } from "../interfaces/IpInfoState";

const MapWithNoSSR = dynamic(() => import("../components/Map"), {
    ssr: false,
});

interface Props {
    state: IpInfoState;
    handleSubmit: (e: React.FormEvent<HTMLFormElement>) => Promise<void>;
    handleChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
    pageProps: any;
}

const Home: NextPage<Props> = ({
    state,
    handleSubmit,
    handleChange,
    ...props
}) => {
    return (
        <>
            <Head>
                <title>IP Adress Tracker</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main
                style={{
                    minHeight: "100vh",
                    display: "flex",
                    flexDirection: "column",
                    justifyContent: "center",
                    alignItems: "center",
                }}
            >
                <div
                    style={{
                        height: "30vh",
                        width: 1440,
                        maxWidth: "100%",
                        position: "relative",
                        backgroundImage: "url('/pattern-bg.png')",
                    }}
                >
                    <Form
                        value={state.ip}
                        onChange={handleChange}
                        onSubmit={handleSubmit}
                    />
                </div>

                <div style={{ height: "70vh", width: 1440, maxWidth: "100%" }}>
                    <MapWithNoSSR
                        lat={state.ipInfo?.latitude || 18.4860575}
                        lng={state.ipInfo?.longitude || -69.9312117}
                        popupText={state.ipInfo?.ip || "Loading..."}
                    />
                </div>
            </main>
        </>
    );
};

export default Home;
