import type { NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";
import Form from "../components/Form";
import { IpInfoState } from "../interfaces/IpInfoState";
import Info from "../components/Info";

const MapWithNoSSR = dynamic(() => import("../components/Map"), {
  ssr: false,
});

interface Props {
  state: IpInfoState;
  handleSubmit: (e: React.FormEvent<HTMLFormElement>) => Promise<void>;
  handleChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  pageProps: any;
}

const Home: NextPage<Props> = ({
  state,
  handleSubmit,
  handleChange,
  ...props
}) => {
  return (
    <>
      <Head>
        <title>IP Adress Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center min-h-screen h-screen">
        <div
          style={{ backgroundImage: "url('/pattern-bg.png')" }}
          className="flex flex-col items-center w-[1440px] max-w-full h-[200px]"
        >
          <h1 className="text-white text-2xl font-bold py-4">
            IP Address Tracker
          </h1>
          <Form
            value={state.ip}
            onChange={handleChange}
            onSubmit={handleSubmit}
          />
        </div>

        {state.ipInfo && (
          <div
            className="flex flex-row flex-wrap justify-around py-3 px-3 rounded-lg max-w-[80%] bg-white shadow-lg z-20"
            style={{ position: "absolute", top: "120px" }}
          >
            <Info title="ip address" description={state.ipInfo.ip} />
            <Info title="location" description={state.ipInfo.city} />
            <Info title="timezone" description={state.ipInfo.timezone_gmt} />
            <Info title="isp" description={state.ipInfo.isp} />
          </div>
        )}

        <div
          style={{ height: "calc(100vh - 200px)" }}
          className="max-w-full w-[1440px] max-h-full z-10"
        >
          {state.ipInfo && (
            <MapWithNoSSR
              lat={state.ipInfo.latitude}
              lng={state.ipInfo.longitude}
              popupText={state.ipInfo.ip}
            />
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
